use_frameworks!

platform :ios, '12.0'

target 'XMGesturePassword_Example' do
  pod 'XMGesturePassword', :path => '../'

  target 'XMGesturePassword_Tests' do
    inherit! :search_paths

    
  end
end
